[tool.black]
line-length = 88
target-version = ['py36','py37','py38']
skip-string-normalization = true
quiet = true
exclude='''
/(
    \.git
  | \.hg
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
